MERGE INTO MPA KEY (MPA_ID,  NAME_MPA) VALUES (1, 'G');
MERGE INTO MPA KEY (MPA_ID,  NAME_MPA) VALUES (2, 'PG');
MERGE INTO MPA KEY (MPA_ID,  NAME_MPA) VALUES (3, 'PG-13');
MERGE INTO MPA KEY (MPA_ID,  NAME_MPA) VALUES (4, 'R');
MERGE INTO MPA KEY (MPA_ID,  NAME_MPA) VALUES (5, 'NC-17');

MERGE INTO GENRE KEY (GENRE_ID, NAME_GENRE) VALUES (1, 'Комедия');
MERGE INTO GENRE KEY (GENRE_ID, NAME_GENRE) VALUES (2, 'Драма');
MERGE INTO GENRE KEY (GENRE_ID, NAME_GENRE) VALUES (3, 'Мультфильм');
MERGE INTO GENRE KEY (GENRE_ID, NAME_GENRE) VALUES (4, 'Фантастика');
MERGE INTO GENRE KEY (GENRE_ID, NAME_GENRE) VALUES (5, 'Ужасы');
MERGE INTO GENRE KEY (GENRE_ID, NAME_GENRE) VALUES (6, 'Мелодрама');